### ISSUE TITLE
老哥在吗 方便交流下吗

### ISSUE THREAD

**Issue by Wangzhen0127** [ElysiaEgo/FaerieKingdomBackend#1]

**Comment by ElysiaEgo** [comment]
邮箱联系

**Comment by Wangzhen0127** [comment]
老哥你那个是fgo的后台吗？你这前台vue的api我没跑懂，后台是先弄数据库？Profile · Faerie Kingdom | Made by elysiaEgo这个是您那后台吗？我这登录显示Cannot read properties of undefined (reading 'toString')
&nbsp;


1153478116
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月28日(星期天) 下午5:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ElysiaEgo/FaerieKingdomBackend] 老哥在吗 方便交流下吗 (Issue #1)





 
邮箱联系

**Comment by heqyoufree** [comment]
前端只是静态文件，build完之后就行，后端执行yarn run build之后执行生成的js文件

从 Windows 版邮件发送

发件人: Wangzhen0127
发送时间: 2023年5月28日 17:42
收件人: ElysiaEgo/FaerieKingdomBackend
抄送: Subscribed
主题: Re: [ElysiaEgo/FaerieKingdomBackend] 老哥在吗 方便交流下吗 (Issue #1)

老哥你那个是fgo的后台吗？你这前台vue的api我没跑懂，后台是先弄数据库？Profile · Faerie Kingdom | Made by elysiaEgo这个是您那后台吗？我这登录显示Cannot read properties of undefined (reading 'toString') 
&nbsp; 


1153478116 
***@***.*** 



&nbsp; 




------------------&nbsp;原始邮件&nbsp;------------------ 
发件人: ***@***.***&gt;; 
发送时间: 2023年5月28日(星期天) 下午5:38 
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ElysiaEgo/FaerieKingdomBackend] 老哥在吗 方便交流下吗 (Issue #1) 






邮箱联系
